---
image: debian:buster

before_script:
  - apt-get update
  - apt-get install -y dpkg-dev devscripts wget git
  - wget "https://code.fe80.eu/$CI_PROJECT_NAMESPACE/libosmocore/-/jobs/artifacts/master/download?job=build-deb" -O libosmocore.zip
  - unzip libosmocore.zip
  - cd debs/ && dpkg-scanpackages . > Packages
  - echo "deb [trusted=yes] file://$PWD ./" > /etc/apt/sources.list.d/local.list
  - cd ..
  - apt-get update

build-deb:
  stage: build
  script:
  - yes "" | mk-build-deps -i
  - dpkg-buildpackage -us -uc
  - rm -rf debs/
  - mkdir -p debs/
  - cp ../*.deb ../*.dsc ../*.tar* ../*.buildinfo ../*changes debs/
  - ls -al ../
  artifacts:
    paths:
    - debs/libosmo-abis*
